version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - app-network

  ms-event-manager:
    build:
      context: ./event-manager
    ports:
      - '8080:8080'
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/scholarship-ship-desafio3
      SERVER_PORT: 8080
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - app-network

  ms-ticket-manager:
    build:
      context: ./ticket-manager
    ports:
      - '8081:8081'
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/scholarship-ship-desafio3
      SERVER_PORT: 8081
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
